name: CI
on:
  create:
    tags:
      - v*
jobs:
  macos:
    runs-on: macos-latest
    steps:
    - name: Install coreutils
      run: brew install coreutils
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Build tdlib for mac os
      run: /bin/bash macos.sh
