name: MacOS + Linux
on:
  create:
    tags:
      - v*
jobs:
  macos:
    runs-on: macos-latest
    steps:
    - name: Install coreutils
      run: brew install coreutils
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Build tdlib for mac os
      run: /bin/bash macos.sh
    - name: Copy files 
      run : cp
    - name: Commit files
      run: |
        cp -r  ~/td/tdlib/bin/ ./
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add libtdjni.dylib com
        git commit -m "Update MacOS binaries"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}