name: Linux
on:
  create:
    tags:
      - v*
jobs:
  ubuntu18.04 build:
    runs-on: ubuntu-18_04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Build tdlib for Ubuntu
      run: /bin/bash linux-ubuntu-18.sh
    - name: Commit files
      run: |
        cp -r td/tdlib/bin/ ./
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add libtdjni.so com
        git commit -m "Update Linux binaries"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
