name: Linux
on:
  schedule:
    - cron: "0 0 1 * *"
  create:
    tags:
      - v*
jobs:
  ubuntu:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        ref: master
    - name: Build tdlib for Ubuntu
      run: /bin/bash linux-ubuntu-18.sh
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
