name: MacOS
on:
  schedule:
    - cron: "0 0 1 * *"   
  create:
    tags:
      - v*
jobs:
  macos:
    runs-on: macos-latest
    steps:
    - name: Install coreutils
      run: brew install coreutils
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        ref: master
    - name: Build tdlib for mac os
      run: /bin/bash macos.sh
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
