name: CI
on: 
  release:
    types:
      - created
jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run:  /bin/bash macos.sh
