name: Windows
on:
  create:
    tags:
      - v*
jobs:
  windows:
    runs-on: windows
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Build tdlib for windows
      run: /bin/bash windows.sh
